# spring.application.name=DHFile
# spring.datasource.url=jdbc:mariadb://localhost:3307/DHFILE
# spring.datasource.password=black
# spring.datasource.username=root
# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# server.servlet.context-path=/api
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
# spring.jpa.hibernate.ddl-auto=update

spring:
    datasource:
        url: jdbc:mariadb://localhost:3307/DHFILE
        username: root
        password: black
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        show-sql: true
        properties:
            hibernate.format_sql: true               
            database: mariadb
            database-platform: org.hibernate.dialect.MariaDBDialect
server:
    servlet:
        context-path: /api